  /**
   * Credentials
   */
 // *** DATA FOUNDRY SERVER ADDRESS ***
 const char* DF_BASE_URL = "data.id.tue.nl";

 // **************************************DEPLOYMENT******************************************
 // *********************************
 // *** Data Foundry project meta ***
 // **********************************
 const char* USER_ID                 = "<PARTICIPANT_USER_ID>";
 const char* WIFI_SSID               = "<WIFI_SSID>"; //ssid of wifi network
 const char* WIFI_PIN                = "<WIFI_PIN>"; //password of local wifi network
 const char* IOT_DATASET_1_TOKEN     = "<DATA_FOUNDRY_IOT_DATASET_TOKEN>";
 const int  IOT_DATASET_1_ID         = -1; // *** NOTE: CHANGE TO THE IOT DATASET ID (IN DATA FOUNDRY) IN YOUR OWN PROJECT
 const char* SUGAR_TRACKER_DEVICE_ID = "<DEVICE_ID_ATTACHED_TO_THE_PARTICIPANT>";  // *** DEVICE REFERENCE ID GENERATED BY DATA FOUNDRY ***
 // ******************************************************************************************
